### ISSUE TITLE
Gurobi license

### ISSUE THREAD

**Issue by andreyurch** [raphael-group/ConDoR#7]
Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (mac64[x86] - Darwin 22.6.0 22G436)

CPU model: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Thread count: 4 physical cores, 4 logical processors, using up to 1 threads

Traceback (most recent call last):
  File "src/condor.py", line 98, in <module>
    main(args)
  File "src/condor.py", line 68, in main
    solver.solveSetInclusion()
  File "/Users/testaccount/Documents/app/ConDoR/src/solveConstrainedDollo.py", line 290, in solveSetInclusion
    model.optimize()
  File "src/gurobipy/model.pxi", line 893, in gurobipy.Model.optimize
gurobipy.GurobiError: Model too large for size-limited license; visit https://gurobi.com/unrestricted for more information

**Comment by sashitt2** [comment]
I think you need a more unrestricted gurobi license. I recommend using the free academic license if you belong to a academic institute.
